version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install databricks-cli
            pip install pyyaml

      - run:
          name: Set .databrickscfg
          command: |
            echo "[DEFAULT]" >> ~/.databrickscfg
            echo "host=$PROD_DATABRICKS_SHARD" >> ~/.databrickscfg
            echo "username=viren.patel@databricks.com" >> ~/.databrickscfg
            echo "token=$PROD_DATABRICKS_TOKEN" >> ~/.databrickscfg
            cat ~/.databrickscfg

      - run:
          name: Copy Notebooks to "Prod"
          command: |
            . venv/bin/activate
            # databricks workspace rm -r /git-notebooks/
            databricks workspace import_dir -o ./git-notebooks /git-notebooks

      - run:
          name: Databricks Job Create/Update
          command: |
            . venv/bin/activate
            cd ~/project/deploy-scripts
            python job-deploy.py

      - run:
          name: Update Permissions on Notebooks/Jobs
          command: |
            . venv/bin/activate
            cd ~/project/deploy-scripts
            python permission-setter.py
