version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/python:3.7.0

    steps:
      - checkout

      - run:
          name: TEST
          command: echo "HELLO"